data:
  data_path: '/apdcephfs/share_1364275/jiaqihan/atom3d/new_data'
  seed: 1

model:
  name: 'EGNN'
  hidden_dim: 64
  n_layers: 4

task:

trainer:
  exp_name: 'atom3d_lep_demo'
  model_save_path: 'saved_models'
#  model_save_path: '/apdcephfs/share_1364275/jiaqihan/pysign_exps/exp_files/atom3d_lep'
  batch_size: 8
  seed: 1
  epoch: 1000
  eval_epoch: 1
  earlystopping: 40
  optimizer:
    name: 'Adam'
    lr: 0.0005
    weight_decay: 1.0e-10
  scheduler:
    name: 'Plateau'
    factor: 0.5
    patience: 20
  save_pred: false
