data:
  data_path: '/apdcephfs/share_1364275/jiaqihan/pysign_exps/cached_datasets/md17'
  molecule: 'aspirin'
  seed: 1

model:
  name: 'schnet'
  hidden_dim: 128
  n_layers: 6
  num_rbf: 20

task:
  charge_power: 0
  max_atom_type: 10
  max_hop: 0
  energy_weight: 0.005
  force_weight: 0.995

trainer:
  exp_name: null
#  model_save_path: 'saved_models'
  model_save_path: '/apdcephfs/share_1364275/jiaqihan/pysign_exps/exp_files_new/md17_ef'
  batch_size: 10
  seed: 1
  epoch: 1500
  eval_epoch: 1
  print_freq: 200
  earlystopping: 40
  optimizer:
    name: 'Adam'
    lr: 0.001
    weight_decay: 1.0e-10
  scheduler:
    name: 'Plateau'
    factor: 0.5
    patience: 50
  save_pred: false
