data:
  data_path: '/apdcephfs/share_1364275/jiaqihan/pysign_exps/cached_datasets/md17'
  molecule: 'aspirin'
  seed: 1

model:
  name: 'tfn'
  hidden_dim: 32
  n_layers: 7
  num_nlayers: 1
  num_degrees: 3

task:
  charge_power: 0
  max_atom_type: 10
  energy_weight: 0.2
  force_weight: 0.8

trainer:
  exp_name: null
#  model_save_path: 'saved_models'
  model_save_path: '/apdcephfs/share_1364275/jiaqihan/pysign_exps/exp_files_new/md17_ef'
  batch_size: 32
  seed: 1
  epoch: 3000
  eval_epoch: 1
  print_freq: 200
  earlystopping: 200
  optimizer:
    name: 'Adam'
    lr: 0.0005
    weight_decay: 1.0e-10
  scheduler:
    name: 'Plateau'
    factor: 0.5
    patience: 40
  save_pred: false
