name: test

on:
  push:
    branches:    
      - main

jobs:

  nbody-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install pytorch geometric dependencies
        run: |
          pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch-geometric==2.0.4
          pip install torch_scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.7.1+cpu.html
          pip install torch_sparse==0.6.9 -f https://data.pyg.org/whl/torch-1.7.1+cpu.html
          pip install torch_cluster==1.5.8 -f https://data.pyg.org/whl/torch-1.7.1+cpu.html
      - name: Install miscellaneous dependencies
        run: |
          pip install tqdm
          pip install matplotlib
          pip install sympy
          pip install pyyaml
      - name: Install atom3d dependencies
        run: |
          pip install atom3d
      - name: Install dgl dependencies
        run: |
          pip install dgl==0.4.3.post2
          pip install lie-learn

      - name: Run Nbody System
        run: |
          python examples/nbody_test.py